name: hris
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  trust_location: ^2.0.13
  geocoding: ^2.0.4
  geolocator: ^9.0.1
  font_awesome_flutter: ^10.1.0
  path: ^1.8.2
  photo_view: ^0.14.0
  datetime_picker_formfield_new: ^2.0.0
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0
  pdf_render: ^1.1.0
  flutter_masked_text2: ^0.9.1
  webview_flutter: ^3.0.4
  device_info_plus: ^3.2.4
  lottie: ^1.4.0
  image_picker: ^0.8.5+3
  flutter_barcode_scanner: ^2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
